version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    depends_on:
      - db
    environment:
      - DATABASE_URL=file:/db/dev.db
    volumes:
      - db_data:/db
    networks:
      - app_network

  db:
    build:
      context: .
      dockerfile: Dockerfile_sqlite
    environment:
      - DATABASE_URL=file:/db/dev.db
    volumes:
      - db_data:/db
    command: ["sh", "-c", "npx prisma generate && npx prisma migrate deploy --schema=/db/prisma/schema.prisma && tail -f /dev/null"]
    networks:
      - app_network

volumes:
  db_data:
    driver: local

networks:
  app_network:
    driver: bridge
